// Mocks generated by Mockito 5.0.7 from annotations
// in mister_delivery_flutter/test/modules/foods/domain/usecases/get_food_details_usecase_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mister_delivery_flutter/app/modules/foods/domain/entities/response/extra_entity.dart'
    as _i4;
import 'package:mister_delivery_flutter/app/modules/foods/domain/entities/response/food_entity.dart'
    as _i3;
import 'package:mister_delivery_flutter/app/modules/foods/domain/errors/errors.dart'
    as _i7;
import 'package:mister_delivery_flutter/app/modules/foods/domain/repositories/get_food_details_repository.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [FoodEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodEntity extends _i1.Mock implements _i3.FoodEntity {
  MockFoodEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: 0) as int);
  @override
  String get imageUrl =>
      (super.noSuchMethod(Invocation.getter(#imageUrl), returnValue: '')
          as String);
  @override
  String get name =>
      (super.noSuchMethod(Invocation.getter(#name), returnValue: '') as String);
  @override
  num get price =>
      (super.noSuchMethod(Invocation.getter(#price), returnValue: 0) as num);
  @override
  String get description =>
      (super.noSuchMethod(Invocation.getter(#description), returnValue: '')
          as String);
  @override
  bool get hasDetails =>
      (super.noSuchMethod(Invocation.getter(#hasDetails), returnValue: false)
          as bool);
  @override
  List<_i4.ExtraEntity> get extras =>
      (super.noSuchMethod(Invocation.getter(#extras),
          returnValue: <_i4.ExtraEntity>[]) as List<_i4.ExtraEntity>);
  @override
  String get priceFormatted =>
      (super.noSuchMethod(Invocation.getter(#priceFormatted), returnValue: '')
          as String);
}

/// A class which mocks [IGetFoodDetailsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGetFoodDetailsRepository extends _i1.Mock
    implements _i5.IGetFoodDetailsRepository {
  MockIGetFoodDetailsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i7.FailureFood, _i3.FoodEntity>> getFood(int? id) =>
      (super.noSuchMethod(Invocation.method(#getFood, [id]),
              returnValue:
                  Future<_i2.Either<_i7.FailureFood, _i3.FoodEntity>>.value(
                      _FakeEither<_i7.FailureFood, _i3.FoodEntity>()))
          as _i6.Future<_i2.Either<_i7.FailureFood, _i3.FoodEntity>>);
}
