// Mocks generated by Mockito 5.0.7 from annotations
// in mister_delivery_flutter/test/modules/cart/infra/repositories/get_cart_repository_implementation_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mister_delivery_flutter/app/modules/cart/domain/entities/response/cart_food_response_entity.dart'
    as _i4;
import 'package:mister_delivery_flutter/app/modules/cart/infra/datasource/get_cart_datasource.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [IGetCartDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGetCartDatasource extends _i1.Mock
    implements _i2.IGetCartDatasource {
  MockIGetCartDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CartFoodResponseEntity>> getCart() =>
      (super.noSuchMethod(Invocation.method(#getCart, []),
              returnValue: Future<List<_i4.CartFoodResponseEntity>>.value(
                  <_i4.CartFoodResponseEntity>[]))
          as _i3.Future<List<_i4.CartFoodResponseEntity>>);
}
