// Mocks generated by Mockito 5.0.7 from annotations
// in mister_delivery_flutter/test/modules/foods/infra/repositories/add_food_to_cart_implementation_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mister_delivery_flutter/app/modules/foods/domain/entities/request/cart_extra_request_entity.dart'
    as _i3;
import 'package:mister_delivery_flutter/app/modules/foods/domain/entities/request/cart_food_request_entity.dart'
    as _i2;
import 'package:mister_delivery_flutter/app/modules/foods/infra/datasources/add_food_to_cart_datasource.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [CartFoodRequestEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartFoodRequestEntity extends _i1.Mock
    implements _i2.CartFoodRequestEntity {
  MockCartFoodRequestEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: 0) as int);
  @override
  int get quantity =>
      (super.noSuchMethod(Invocation.getter(#quantity), returnValue: 0) as int);
  @override
  List<_i3.CartExtraRequestEntity> get extras =>
      (super.noSuchMethod(Invocation.getter(#extras),
              returnValue: <_i3.CartExtraRequestEntity>[])
          as List<_i3.CartExtraRequestEntity>);
  @override
  String get observation =>
      (super.noSuchMethod(Invocation.getter(#observation), returnValue: '')
          as String);
}

/// A class which mocks [IAddFoodToCartDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAddFoodToCartDatasource extends _i1.Mock
    implements _i4.IAddFoodToCartDatasource {
  MockIAddFoodToCartDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> addFoodToCart(_i2.CartFoodRequestEntity? food) =>
      (super.noSuchMethod(Invocation.method(#addFoodToCart, [food]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
}
