// Mocks generated by Mockito 5.0.7 from annotations
// in mister_delivery_flutter/test/modules/foods/infra/repositories/get_food_details_implementation_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mister_delivery_flutter/app/modules/foods/domain/entities/response/extra_entity.dart'
    as _i3;
import 'package:mister_delivery_flutter/app/modules/foods/infra/datasources/get_food_details_datasource.dart'
    as _i4;
import 'package:mister_delivery_flutter/app/modules/foods/infra/models/response/food_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeFoodModel extends _i1.Fake implements _i2.FoodModel {}

/// A class which mocks [FoodModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodModel extends _i1.Mock implements _i2.FoodModel {
  MockFoodModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: 0) as int);
  @override
  String get imageUrl =>
      (super.noSuchMethod(Invocation.getter(#imageUrl), returnValue: '')
          as String);
  @override
  String get name =>
      (super.noSuchMethod(Invocation.getter(#name), returnValue: '') as String);
  @override
  num get price =>
      (super.noSuchMethod(Invocation.getter(#price), returnValue: 0) as num);
  @override
  String get description =>
      (super.noSuchMethod(Invocation.getter(#description), returnValue: '')
          as String);
  @override
  bool get hasDetails =>
      (super.noSuchMethod(Invocation.getter(#hasDetails), returnValue: false)
          as bool);
  @override
  List<_i3.ExtraEntity> get extras =>
      (super.noSuchMethod(Invocation.getter(#extras),
          returnValue: <_i3.ExtraEntity>[]) as List<_i3.ExtraEntity>);
}

/// A class which mocks [IGetFoodDetailsDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGetFoodDetailsDatasource extends _i1.Mock
    implements _i4.IGetFoodDetailsDatasource {
  MockIGetFoodDetailsDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.FoodModel> getFood(int? id) =>
      (super.noSuchMethod(Invocation.method(#getFood, [id]),
              returnValue: Future<_i2.FoodModel>.value(_FakeFoodModel()))
          as _i5.Future<_i2.FoodModel>);
}
